from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import io
import re


# ── Color constants ──────────────────────────────────────────────────────────
BLUE = colors.HexColor("#1A5FA8")
BLACK = colors.HexColor("#1A1A1A")
LIGHT_BLUE_BG = colors.HexColor("#EAF2FB")
WHITE = colors.white
GRAY = colors.HexColor("#666666")
LIGHT_GRAY = colors.HexColor("#F5F5F5")


# ── Styles ───────────────────────────────────────────────────────────────────
def build_styles():
    return {
        "cover_title": ParagraphStyle(
            "cover_title",
            fontName="Helvetica-Bold",
            fontSize=28,
            textColor=WHITE,
            alignment=TA_LEFT,
            leading=34,
        ),
        "cover_sub": ParagraphStyle(
            "cover_sub",
            fontName="Helvetica",
            fontSize=13,
            textColor=colors.HexColor("#D0E8FF"),
            alignment=TA_LEFT,
            leading=18,
        ),
        "section_heading": ParagraphStyle(
            "section_heading",
            fontName="Helvetica-Bold",
            fontSize=13,
            textColor=BLUE,
            leading=18,
            spaceBefore=14,
            spaceAfter=4,
            leftIndent=0,
        ),
        "numbered_point": ParagraphStyle(
            "numbered_point",
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=BLACK,
            leading=15,
            spaceBefore=3,
            spaceAfter=2,
            leftIndent=18,
        ),
        "body": ParagraphStyle(
            "body",
            fontName="Helvetica",
            fontSize=10,
            textColor=colors.HexColor("#333333"),
            leading=15,
            spaceBefore=2,
            spaceAfter=2,
            leftIndent=0,
        ),
        "toc_item": ParagraphStyle(
            "toc_item",
            fontName="Helvetica",
            fontSize=11,
            textColor=colors.HexColor("#333333"),
            leading=20,
            leftIndent=12,
        ),
        "footer": ParagraphStyle(
            "footer",
            fontName="Helvetica",
            fontSize=8,
            textColor=GRAY,
            alignment=TA_CENTER,
        ),
    }


# ── Cover page builder ────────────────────────────────────────────────────────
def build_cover(story, styles, client_name: str, date_str: str):
    from reportlab.platypus import Table, TableStyle
    from reportlab.lib.units import inch

    # Blue banner as a colored table cell
    cover_data = [[
        Paragraph("PROJECT PROPOSAL", styles["cover_title"])
    ]]
    cover_table = Table(cover_data, colWidths=[470])
    cover_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BLUE),
        ("TOPPADDING", (0, 0), (-1, -1), 36),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 36),
        ("LEFTPADDING", (0, 0), (-1, -1), 24),
        ("RIGHTPADDING", (0, 0), (-1, -1), 24),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [BLUE]),
    ]))
    story.append(cover_table)
    story.append(Spacer(1, 16))

    if client_name:
        story.append(Paragraph(f"Prepared for: <b>{client_name}</b>", styles["body"]))
    story.append(Paragraph(f"Generated by: <b>VirtualEmployee.com</b>", styles["body"]))
    story.append(Paragraph(f"Date: {date_str}", styles["body"]))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CCCCCC")))
    story.append(Spacer(1, 20))


# ── Line classifier ───────────────────────────────────────────────────────────
SECTION_HEADING_RE = re.compile(
    r"^(\d+\s+[A-Z][A-Z\s&/]+|CONTENTS|COMPANY OVERVIEW|PURPOSE OF THE DOCUMENT|"
    r"KEY DELIVERABLES|OBJECTIVES|FEATURES AND FUNCTIONALITY|TECHNICAL APPROACH|"
    r"TECHNOLOGY STACK|FUTURE SCOPE|TIME AND BUDGET ESTIMATE)$"
)
NUMBERED_POINT_RE = re.compile(r"^\d+[\.\)]\s+.+|^\d+\.\d+[\.\)]?\s+.+")
BULLET_RE = re.compile(r"^[-•\*]\s+.+")


def classify_line(line: str):
    stripped = line.strip()
    if not stripped:
        return "empty", stripped
    if SECTION_HEADING_RE.match(stripped):
        return "heading", stripped
    if NUMBERED_POINT_RE.match(stripped):
        return "numbered", stripped
    if BULLET_RE.match(stripped):
        return "bullet", stripped
    return "body", line.rstrip()


# ── Main PDF creator ──────────────────────────────────────────────────────────
def create_proposal_pdf(proposal_text: str, client_name: str = "") -> bytes:
    from datetime import datetime

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=60,
        rightMargin=60,
        topMargin=50,
        bottomMargin=60,
        title="Project Proposal",
        author="VirtualEmployee.com",
    )

    styles = build_styles()
    story = []

    date_str = datetime.now().strftime("%d %B %Y")
    build_cover(story, styles, client_name, date_str)

    lines = proposal_text.split("\n")
    for raw_line in lines:
        kind, text = classify_line(raw_line)

        if kind == "empty":
            story.append(Spacer(1, 4))

        elif kind == "heading":
            story.append(Spacer(1, 6))
            story.append(HRFlowable(width="100%", thickness=0.4, color=colors.HexColor("#D0E0F0")))
            story.append(
                Paragraph(
                    f'<font color="#1A5FA8"><b>{text}</b></font>',
                    styles["section_heading"],
                )
            )

        elif kind == "numbered":
            story.append(Paragraph(text, styles["numbered_point"]))

        elif kind == "bullet":
            clean = re.sub(r"^[-•\*]\s+", "", text)
            story.append(Paragraph(f"• {clean}", styles["numbered_point"]))

        else:
            if text.strip():
                story.append(Paragraph(text.strip(), styles["body"]))

    def add_page_number(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(GRAY)
        page_num = canvas.getPageNumber()
        canvas.drawString(60, 30, "VirtualEmployee.com — Confidential")
        canvas.drawRightString(A4[0] - 60, 30, f"Page {page_num}")
        canvas.restoreState()

    doc.build(story, onFirstPage=add_page_number, onLaterPages=add_page_number)
    return buffer.getvalue()