import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import mermaid from "mermaid";
import logoUrl from "../assets/logo.png";

mermaid.initialize({
  startOnLoad: false,
  theme: 'default',
  securityLevel: 'loose',
  fontFamily: 'helvetica',
  flowchart: { htmlLabels: false },
  er: { htmlLabels: false },
  sequence: { showSequenceNumbers: false },
  markdown: false // Disable markdown which heavily uses foreignObject
});

function stripForeignObjects(svg) {
  return svg.replace(
    /<foreignObject[^>]*>([\s\S]*?)<\/foreignObject>/gi,
    (_match, inner) => {
      // Re-extract the original attributes from the match to get bounding box
      const attrsMatch = _match.match(/<foreignObject([^>]*)>/i);
      const attrs = attrsMatch ? attrsMatch[1] : '';
      
      const wMatch = attrs.match(/width="([^"]+)"/i);
      const hMatch = attrs.match(/height="([^"]+)"/i);
      const xMatch = attrs.match(/x="([^"]+)"/i);
      const yMatch = attrs.match(/y="([^"]+)"/i);
      
      const w = wMatch ? parseFloat(wMatch[1]) : 0;
      const h = hMatch ? parseFloat(hMatch[1]) : 0;
      const x = xMatch ? parseFloat(xMatch[1]) : 0;
      const y = yMatch ? parseFloat(yMatch[1]) : 0;

      // Extract text content, converting <br> to newlines
      let textContent = inner.replace(/<br[^>]*>/gi, '\n');
      textContent = textContent.replace(/<[^>]+>/g, '').trim();

      // Escape XML entities
      textContent = textContent
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");

      const lines = textContent.split('\n');
      const fontSize = 12;
      const lineHeight = fontSize * 1.2;
      const totalTextHeight = lines.length * lineHeight;
      
      // Calculate Y so the text block is vertically centered in the bounding box
      const centerY = y + (h / 2);
      const startY = centerY - (totalTextHeight / 2) + (lineHeight / 2);
      // Offset for baseline alignment
      const baselineOffset = fontSize * 0.35;

      let textNodes = '';
      lines.forEach((line, i) => {
        const lineY = startY + i * lineHeight + baselineOffset;
        textNodes += `<text x="${x + w / 2}" y="${lineY}" font-size="${fontSize}" font-family="helvetica" fill="#2C3E50" text-anchor="middle">${line}</text>`;
      });

      return textNodes;
    }
  );
}

function prepareSvgForPdf(svgString) {
  const parser = new DOMParser();
  const doc = parser.parseFromString(svgString, 'image/svg+xml');

  // Check for parser errors (malformed XML) before proceeding
  const parserError = doc.querySelector('parsererror');
  if (parserError) {
    console.error('SVG parse error:', parserError.textContent);
    throw new Error('Invalid SVG markup');
  }

  const svgEl = doc.documentElement;

  // Extract dimensions from viewBox if present and set them explicitly
  const viewBox = svgEl.getAttribute('viewBox');
  if (viewBox) {
    const parts = viewBox.trim().split(/\s+/);
    if (parts.length === 4) {
      svgEl.setAttribute('width', parts[2]);
      svgEl.setAttribute('height', parts[3]);
    }
  }

  // Ensure xmlns is present (required for standalone SVG parsing as an Image)
  if (!svgEl.getAttribute('xmlns')) {
    svgEl.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
  }

  // Remove external style imports that cause canvas tainting
  const styles = svgEl.querySelectorAll('style');
  styles.forEach(style => {
    style.textContent = style.textContent.replace(/@import\s+url\([^)]+\);?/g, '');
  });

  return new XMLSerializer().serializeToString(svgEl);
}

async function renderMermaidToPngDataUrl(mermaidCode) {
  let svg;
  try {
    const id = `mermaid-pdf-${Math.random().toString(36).substr(2, 9)}`;
    // Sanitize LLM-generated code: quote labels containing parentheses
    const sanitized = mermaidCode
      .replace(/\[([^\]"]*[()][^\]"]*)\]/g, '["$1"]')
      .replace(/\{([^}"]*[()][^}"]*)\}/g, '{"$1"}');
    const rendered = await mermaid.render(id, sanitized);
    svg = rendered.svg;

    // 1. Fix common invalid XML entities and tags generated by Mermaid or LLM text
    svg = svg.replace(/&nbsp;/g, '&#160;');
    svg = svg.replace(/<br>/gi, '<br/>');
    svg = svg.replace(/<hr>/gi, '<hr/>');
    // Escape any raw & that is not part of an XML entity
    svg = svg.replace(/&(?!(amp|lt|gt|quot|apos|#x?[0-9a-fA-F]+);)/g, '&amp;');

    // 2. Strip foreignObject label wrappers
    svg = stripForeignObjects(svg);

    // 3. Prepare the SVG safely using DOMParser
    const cleanSvgString = prepareSvgForPdf(svg);

    return await new Promise((resolve) => {
      const img = new Image();
      // Use a Blob URL rather than a data: URI — browsers are markedly more
      // lenient loading SVGs via Blob URL.
      const blob = new Blob([cleanSvgString], { type: "image/svg+xml;charset=utf-8" });
      const blobUrl = URL.createObjectURL(blob);

      img.onload = function () {
        const canvas = document.createElement("canvas");
        const scale = 2;
        canvas.width = img.width * scale;
        canvas.height = img.height * scale;
        const ctx = canvas.getContext("2d");
        ctx.scale(scale, scale);
        ctx.fillStyle = "#ffffff";
        ctx.fillRect(0, 0, img.width, img.height);
        ctx.drawImage(img, 0, 0);
        URL.revokeObjectURL(blobUrl);
        resolve({ url: canvas.toDataURL("image/png"), width: img.width, height: img.height });
      };
      img.onerror = (err) => {
        console.error(
          "Failed to load SVG into Image for PDF rendering. SVG might contain unsupported features.",
          err
        );
        console.error("Failing SVG (first 2000 chars):", cleanSvgString.slice(0, 2000));
        URL.revokeObjectURL(blobUrl);
        resolve(null);
      };
      img.src = blobUrl;
    });
  } catch (err) {
    console.error("Failed to render mermaid to PNG", err, svg ? svg.slice(0, 2000) : mermaidCode);
    return null;
  }
}

/**
 * Load an image URL (import or remote) as a base64 data URL.
 */
function loadImageAsDataUrl(src) {
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      const ctx = canvas.getContext("2d");
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = () => resolve(null);
    img.src = src;
  });
}

const BLUE = "#31D5B2";
const ORANGE = "#E8962A";
const DARK = "#2C3E50";
const MID = "#555E6D";
const RULE = "#CCCCCC";

const PAGE_W = 210;
const PAGE_H = 297;
const ML = 18;
const MR = 18;
const CW = PAGE_W - ML - MR;

function hexRgb(hex) {
  const h = hex.replace("#", "");
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}
function sc(doc, hex, type = "text") {
  const [r, g, b] = hexRgb(hex);
  type === "text" ? doc.setTextColor(r, g, b) : doc.setFillColor(r, g, b);
}
function sd(doc, hex) { const [r, g, b] = hexRgb(hex); doc.setDrawColor(r, g, b); }
function tw(doc, text) { return (doc.getStringUnitWidth(text) * doc.getFontSize()) / doc.internal.scaleFactor; }
function wrap(doc, text, maxW, size) { doc.setFontSize(size); return doc.splitTextToSize(text, maxW); }

function drawHeader(doc) {
  // Removed "VIRTUAL EMPLOYEE" text per request
  sd(doc, RULE);
  doc.setLineWidth(0.3);
  doc.line(ML, 17, PAGE_W - MR, 17);
}

function drawCover(doc, { projectTitle, preparedBy, date, logoDataUrl }) {
  // 1. The enlarged Logo image placed at the top (branding text removed)
  if (logoDataUrl) {
    const logoW = 80;  // Significantly enlarged logo
    const logoH = 26;  // Maintained aspect ratio
    const logoX = (PAGE_W - logoW) / 2;
    doc.addImage(logoDataUrl, 'PNG', logoX, 30, logoW, logoH);
  }

  // 3. PROPOSAL FOR
  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  sc(doc, BLUE);
  const pf = "PROPOSAL FOR";
  doc.text(pf, (PAGE_W - tw(doc, pf)) / 2, 88);

  // 4. Project Title
  let ty = 101;
  if (projectTitle && projectTitle.trim()) {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    sc(doc, ORANGE);
    const titleLines = wrap(doc, projectTitle.trim(), CW - 10, 16);
    titleLines.forEach((line) => {
      doc.text(line, (PAGE_W - tw(doc, line)) / 2, ty);
      ty += 9;
    });
  }

  // Calculate where the details section should start
  let detailsY = Math.max(140, ty + 20);

  // 5. First Dark Bar
  sc(doc, DARK, "fill");
  doc.rect(ML, detailsY, CW, 8, "F");

  detailsY += 16;

  // 6. Prepared By & Date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  sc(doc, DARK);
  doc.text("Prepared By:", ML + 15, detailsY);
  sc(doc, BLUE);
  doc.text(preparedBy || "Virtual Employee", ML + 55, detailsY);

  detailsY += 10;
  sc(doc, DARK);
  doc.text("Date:", ML + 15, detailsY);
  sc(doc, BLUE);
  const displayDate = date || new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  doc.text(displayDate, ML + 55, detailsY);

  detailsY += 8;

  // 7. Second Dark Bar
  sc(doc, DARK, "fill");
  doc.rect(ML, detailsY, CW, 8, "F");
}

const H1_RE = /^(\d+)\s+([A-Z][A-Z\s&/,]+)$/;
const H1_STANDALONE_RE = /^(CONTENTS|PURPOSE OF THE DOCUMENT|KEY DELIVERABLES|OBJECTIVES|FEATURES AND FUNCTIONALITY|TECHNICAL APPROACH|TECHNOLOGY STACK|FUTURE SCOPE|TIME AND BUDGET ESTIMATE|WORKFLOW DIAGRAM)$/i;
const BULLET_RE = /^[-•*●]\s+/;
const SUBHEAD_RE = /^(Frontend|Backend|Database|Architecture|Integrations|Security|DevOps|Workflow|Overview|Timeline|Phases|Budget|Other Tools|System Architecture|Testing|Deployment|Monitoring|Authentication|Requirement Analysis|Post[- ]?Launch|Infrastructure|Caching|Real[- ]?Time|Offline|Storage|AI|Automation|Scalability|Performance|Error Handling):\s*/i;
const LIST_HEAD_RE = /^\d+\.\s+[^:]+:\s*$/;
const BOLD_LINE_RE = /^\*\*([^*]+)\*\*\s*$/;

function parseLines(text) {
  const rawLines = text.split("\n");
  const blocks = [];

  let i = 0;
  while (i < rawLines.length) {
    const raw = rawLines[i];
    const t = raw.trim();

    // Check for mermaid block
    if (t.startsWith("```mermaid")) {
      let chartText = "";
      i++;
      while (i < rawLines.length && !rawLines[i].trim().startsWith("```")) {
        chartText += rawLines[i] + "\n";
        i++;
      }
      blocks.push({ kind: "mermaid", text: chartText.trim() });
      i++;
      continue;
    }

    // Check for table block
    if (t.startsWith("|") && t.endsWith("|")) {
      const tableLines = [];
      while (i < rawLines.length && rawLines[i].trim().startsWith("|") && rawLines[i].trim().endsWith("|")) {
        tableLines.push(rawLines[i].trim());
        i++;
      }

      const rows = tableLines.map(line =>
        line.split("|").slice(1, -1).map(cell => cell.trim().replace(/\*\*/g, "")) // simple bold strip for pdf
      );

      if (rows.length >= 2 && rows[1].every(cell => cell.match(/^[-:]+$/))) {
        blocks.push({
          kind: "table",
          headers: rows[0],
          data: rows.slice(2),
        });
      } else {
        // Fallback
        tableLines.forEach(tLine => {
          if (!tLine) blocks.push({ kind: "empty" });
          else blocks.push({ kind: "body", text: tLine });
        });
      }
      continue;
    }

    // Regular line
    if (!t) { blocks.push({ kind: "empty" }); }
    else if (H1_RE.test(t)) { const [, num, title] = t.match(H1_RE); blocks.push({ kind: "h1", num, title }); }
    else if (H1_STANDALONE_RE.test(t)) { blocks.push({ kind: "h1", num: "", title: t }); }
    else if (BULLET_RE.test(t)) { blocks.push({ kind: "bullet", text: t.replace(/^[-•*●]\s+/, "") }); }
    else if (SUBHEAD_RE.test(t)) { blocks.push({ kind: "sub", text: t }); }
    else if (LIST_HEAD_RE.test(t)) { blocks.push({ kind: "sub", text: t }); }
    else if (BOLD_LINE_RE.test(t)) { blocks.push({ kind: "sub", text: t.replace(/\*\*/g, "") }); }
    else { 
      const last = blocks[blocks.length - 1];
      if (last && (last.kind === "body" || last.kind === "bullet" || last.kind === "sub")) {
        last.text += " " + t;
      } else {
        blocks.push({ kind: "body", text: t }); 
      }
    }

    i++;
  }
  return blocks;
}

function drawTOC(doc, sections) {
  drawHeader(doc);
  let y = 28;
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  sc(doc, BLUE);
  doc.text("Contents", ML, y);
  y += 10;
  sections.forEach(({ num, title, page, indent }) => {
    const isMajor = indent === 0;
    doc.setFontSize(isMajor ? 10.5 : 9.5);
    doc.setFont("helvetica", isMajor ? "bold" : "normal");
    sc(doc, DARK);
    const label = num ? `${num}  ${title}` : title;
    const wrapped = doc.splitTextToSize(label, CW - indent - 12);
    if (y + wrapped.length * 5.2 > PAGE_H - 18) { doc.addPage(); drawHeader(doc); y = 28; }
    wrapped.forEach((line, li) => doc.text(line, ML + indent, y + li * 5.2));
    doc.text(String(page), PAGE_W - MR, y, { align: "right" });
    y += wrapped.length * 5.2 + (isMajor ? 1.5 : 0.8);
  });
}

export async function generateProposalPdf(
  proposalText,
  { projectTitle = "", preparedBy = "Virtual Employee Pvt. Ltd.", clientName = "", date = "" } = {},
) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  doc.setFont("helvetica");

  const cleaned = proposalText.replace(
    /(\n|^)(CONTENTS|\d+\s+CONTENTS)[^\n]*\n([\s\S]*?)(?=(\n|^)\d+\s+[A-Z][A-Z])/gm, "\n"
  );

  const parsed = parseLines(cleaned);
  const PAGE_BOTTOM = PAGE_H - 18;
  let simPage = 3, simY = 26;
  const tocEntries = [];
  function simBreak(n) { if (simY + n > PAGE_BOTTOM) { simPage++; simY = 26; } }

  for (const e of parsed) {
    switch (e.kind) {
      case "empty": simY += 2; break;
      case "h1": simBreak(14); simY += 5; tocEntries.push({ num: e.num, title: e.title, page: simPage, indent: 0 }); simY += 6; break;
      case "sub": simBreak(8); simY += 2; tocEntries.push({ num: "", title: e.text, page: simPage, indent: 8 }); simY += 6; break;
      case "bullet": { const n = Math.ceil(e.text.length / 80) || 1; simBreak(n * 4.8 + 2); simY += n * 4.8 + 1; break; }
      case "body": { const n = Math.ceil(e.text.length / 90) || 1; simBreak(n * 4.8 + 2); simY += n * 4.8 + 2; break; }
      case "table": { const n = (e.data.length + 1) * 8 + 10; simBreak(n); simY += n; break; }
      case "mermaid": { simBreak(10); simY += 10; break; }
    }
  }

  // Load logo image for cover page
  const logoDataUrl = await loadImageAsDataUrl(logoUrl);
  drawCover(doc, { projectTitle, preparedBy, date, logoDataUrl });

  doc.addPage();
  drawTOC(doc, tocEntries);

  doc.addPage();
  drawHeader(doc);
  let y = 26;
  function pageBreak(n = 10) { if (y + n > PAGE_BOTTOM) { doc.addPage(); drawHeader(doc); y = 26; } }
  function rule() { pageBreak(5); sd(doc, RULE); doc.setLineWidth(0.25); doc.line(ML, y, PAGE_W - MR, y); y += 4; }

  for (const e of parsed) {
    switch (e.kind) {
      case "empty": y += 2; break;
      case "h1":
        pageBreak(14); y += 5;
        doc.setFontSize(12); doc.setFont("helvetica", "bold"); sc(doc, BLUE);
        doc.text(e.num ? `${e.num}  ${e.title}` : e.title, ML, y);
        y += 2; rule(); break;
      case "sub": {
        pageBreak(8); y += 2;
        doc.setFontSize(10); doc.setFont("helvetica", "bold"); sc(doc, DARK);
        const wl = wrap(doc, e.text, CW - 4, 10);
        wl.forEach((line, li) => doc.text(line, ML + 2, y + li * 5));
        y += wl.length * 5 + 1; break;
      }
      case "bullet": {
        const wl = wrap(doc, e.text, CW - 8, 10);
        pageBreak(wl.length * 4.8 + 2);
        doc.setFontSize(10); doc.setFont("helvetica", "normal"); sc(doc, DARK);
        const [r, g, b] = hexRgb(DARK); doc.setFillColor(r, g, b);
        doc.circle(ML + 2.2, y - 1.4, 0.8, "F");
        wl.forEach((line, li) => doc.text(line, ML + 5, y + li * 4.8));
        y += wl.length * 4.8 + 1; break;
      }
      case "body": {
        doc.setFontSize(10); doc.setFont("helvetica", "normal"); sc(doc, DARK);
        const wl = wrap(doc, e.text, CW, 10);
        pageBreak(wl.length * 4.8 + 2);
        wl.forEach((line, li) => doc.text(line, ML, y + li * 4.8));
        y += wl.length * 4.8 + 2; break;
      }
      case "table": {
        autoTable(doc, {
          startY: y,
          head: [e.headers],
          body: e.data,
          theme: 'grid',
          headStyles: { fillColor: hexRgb(BLUE), textColor: 255 },
          margin: { left: ML, right: MR },
          didDrawPage: (data) => {
            // Only update y if we are on the same page, otherwise it gets handled by autoTable
          }
        });
        y = doc.lastAutoTable.finalY + 10;
        break;
      }
      case "mermaid": {
        const imgData = await renderMermaidToPngDataUrl(e.text);
        if (imgData) {
          const maxWidth = CW;
          // Approximate pixel to mm conversion (96dpi)
          let finalW = imgData.width * 0.264583;
          let finalH = imgData.height * 0.264583;

          if (finalW > maxWidth) {
            const ratio = maxWidth / finalW;
            finalW = maxWidth;
            finalH = finalH * ratio;
          }

          // Ensure diagram fits vertically on the page without overlapping footer
          const maxH = PAGE_BOTTOM - 26;
          if (finalH > maxH) {
            const ratio = maxH / finalH;
            finalH = maxH;
            finalW = finalW * ratio;
          }

          pageBreak(finalH + 10);
          doc.addImage(imgData.url, 'PNG', ML + (CW - finalW) / 2, y, finalW, finalH);
          y += finalH + 10;
        } else {
          pageBreak(10);
          doc.setFontSize(10); doc.setFont("helvetica", "italic"); sc(doc, MID);
          doc.text("[ Workflow Diagram rendering failed ]", ML, y);
          y += 10;
        }
        break;
      }
    }
  }

  const total = doc.getNumberOfPages();
  for (let p = 2; p <= total; p++) {
    doc.setPage(p);
    doc.setFontSize(8); doc.setFont("helvetica", "normal"); sc(doc, MID);
    if (clientName) doc.text(`Prepared for: ${clientName}`, ML, PAGE_H - 8);
    if (p >= 3) doc.text(String(p - 2), PAGE_W / 2, PAGE_H - 8, { align: "center" });
    if (preparedBy) doc.text(preparedBy, PAGE_W - MR, PAGE_H - 8, { align: "right" });
  }

  return doc.output("blob");
}